main: main
develop: develop
releaseCandidate: develop
releaseBranches:
  - develop
  - main

enableComments: true

jira:
  project: ENGTEST
  name: DutchieBot Releases - MGG

branchTicketRestrictions:
  'r/hot':
    - EC:
      - Approved
      - Implemented
  main:
    - ENG:
      - 'Ready for Release'